name: Sync OAS to ReadMe
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'swagger-readme.json'
      - 'markdown/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: ${{ secrets.README_OAS_KEY }}
          oas-file-path: './swagger-readme.json'
          api-version: '2019.01.01'
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run python script
        env:
          README_CATEGORY_ID: ${{ secrets.README_CATEGORY_ID }}
          README_API_TOKEN: ${{ secrets.README_API_TOKEN }}
        run: |
          python scripts/readme_orderer.py
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.API_DOCS_SLACK_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C01JAV5FNBW
          status: SUCCESS
          color: good
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.API_DOCS_SLACK_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C01JAV5FNBW
          status: FAILED
          color: danger
